import pythonWasmUrl from 'tree-sitter-python/tree-sitter-python.wasm?url';
import { Language, Parser, type Node } from 'web-tree-sitter';
import treeSitterWasmUrl from 'web-tree-sitter/tree-sitter.wasm?url';

import { MOTION_COMMANDS, POSE_COMMANDS, TRICK_COMMANDS } from './commands.js';

// ── Types ────────────────────────────────────────────────────────────────────

export class ParseError extends Error {
  constructor(
    message: string,
    public readonly line?: number,
  ) {
    super(message);
    this.name = 'ParseError';
  }
}

interface BlockData {
  type: string;
  fields?: Record<string, { value: string; id?: string }>;
  values?: Record<string, BlockData>;
  statements?: Record<string, BlockData[]>;
}

// ── Parser singleton ─────────────────────────────────────────────────────────

let parserSingleton: Parser | null = null;

const getParser = async (): Promise<Parser> => {
  if (parserSingleton) {
    return parserSingleton;
  }

  await Parser.init({
    locateFile: () => treeSitterWasmUrl,
  });

  const Python = await Language.load(pythonWasmUrl);
  const p = new Parser();
  p.setLanguage(Python);
  parserSingleton = p;
  return p;
};

// ── Public API ───────────────────────────────────────────────────────────────

/** Parse MicroPython generated by Doggo Code Blocks and return a Blockly XML element. */
export const parsePython = async (code: string): Promise<Element> => {
  const parser = await getParser();
  const tree = parser.parse(code);
  if (!tree) {
    throw new ParseError('Failed to parse file');
  }
  const root = tree.rootNode;

  if (root.hasError) {
    const errNode = firstErrorNode(root);
    throw new ParseError(
      'Python syntax error — the file could not be parsed',
      errNode ? errNode.startPosition.row + 1 : undefined,
    );
  }

  const vars = new Map<string, string>(); // name → UUID
  const stmts = parseStmtList(namedChildren(root), vars);

  const xml = document.createElement('xml');

  if (vars.size > 0) {
    const variablesEl = document.createElement('variables');
    for (const [name, id] of vars) {
      const v = document.createElement('variable');
      v.setAttribute('id', id);
      v.textContent = name;
      variablesEl.appendChild(v);
    }
    xml.appendChild(variablesEl);
  }

  const hat = document.createElement('block');
  hat.setAttribute('type', 'doggo_on_start');
  hat.setAttribute('x', '10');
  hat.setAttribute('y', '10');
  if (stmts.length > 0) {
    const next = document.createElement('next');
    next.appendChild(makeChain(stmts));
    hat.appendChild(next);
  }
  xml.appendChild(hat);

  return xml;
};

// ── DOM construction ─────────────────────────────────────────────────────────

const makeBlock = (b: BlockData): Element => {
  const el = document.createElement('block');
  el.setAttribute('type', b.type);
  for (const [name, f] of Object.entries(b.fields ?? {})) {
    const field = document.createElement('field');
    field.setAttribute('name', name);
    if (f.id) {
      field.setAttribute('id', f.id);
    }
    field.textContent = f.value;
    el.appendChild(field);
  }
  for (const [name, val] of Object.entries(b.values ?? {})) {
    const value = document.createElement('value');
    value.setAttribute('name', name);
    value.appendChild(makeBlock(val));
    el.appendChild(value);
  }
  for (const [name, stmts] of Object.entries(b.statements ?? {})) {
    if (stmts.length > 0) {
      const stmt = document.createElement('statement');
      stmt.setAttribute('name', name);
      stmt.appendChild(makeChain(stmts));
      el.appendChild(stmt);
    }
  }
  return el;
};

const makeChain = (blocks: BlockData[]): Element => {
  const [head, ...tail] = blocks;
  const el = makeBlock(head);
  if (tail.length > 0) {
    const next = document.createElement('next');
    next.appendChild(makeChain(tail));
    el.appendChild(next);
  }
  return el;
};

// ── Statement parsing ────────────────────────────────────────────────────────

// namedChildren and children return (Node | null)[] in 0.25.x — filter nulls once here.
const namedChildren = (node: Node): Node[] =>
  node.namedChildren.filter((c): c is Node => c !== null);
const allChildren = (node: Node): Node[] => node.children.filter((c): c is Node => c !== null);

const parseStmtList = (nodes: Node[], vars: Map<string, string>): BlockData[] => {
  const result: BlockData[] = [];
  for (const node of nodes) {
    const block = parseStmt(node, vars);
    if (block !== null) {
      result.push(block);
    }
  }
  return result;
};

const parseStmt = (node: Node, vars: Map<string, string>): BlockData | null => {
  const line = node.startPosition.row + 1;
  switch (node.type) {
    case 'import_statement':
    case 'import_from_statement':
    case 'comment':
      return null;

    case 'expression_statement': {
      const expr = namedChildren(node)[0];
      if (!expr) {
        return null;
      }
      if (expr.type === 'call') {
        return parseCallStmt(expr, vars);
      }
      if (expr.type === 'assignment') {
        return parseAssignment(expr, vars, line);
      }
      throw new ParseError(
        `Line ${line}: standalone expressions other than function calls are not supported`,
        line,
      );
    }

    case 'assignment':
      return parseAssignment(node, vars, line);

    case 'for_statement': {
      const iter = node.childForFieldName('right');
      const body = node.childForFieldName('body');
      if (!iter || !body) {
        throw new ParseError(`Line ${line}: malformed for loop`, line);
      }
      if (iter.type !== 'call') {
        throw new ParseError(
          `Line ${line}: for loops must use range(), e.g. for _ in range(5)`,
          line,
        );
      }
      const fn = iter.childForFieldName('function');
      if (!fn || fn.text !== 'range') {
        throw new ParseError(
          `Line ${line}: for loops must use range(), e.g. for _ in range(5)`,
          line,
        );
      }
      const argList = iter.childForFieldName('arguments');
      const argNodes = argList ? namedChildren(argList) : [];
      if (argNodes.length !== 1) {
        throw new ParseError(`Line ${line}: range() must have exactly one argument`, line);
      }
      return {
        type: 'doggo_repeat',
        values: { TIMES: parseExpr(argNodes[0], vars) },
        statements: { SUBSTACK: parseStmtList(namedChildren(body), vars) },
      };
    }

    case 'while_statement': {
      const cond = node.childForFieldName('condition');
      const body = node.childForFieldName('body');
      if (!cond || !body) {
        throw new ParseError(`Line ${line}: malformed while loop`, line);
      }
      const bodyStmts = parseStmtList(namedChildren(body), vars);
      if (cond.type === 'true' || (cond.type === 'identifier' && cond.text === 'True')) {
        return { type: 'doggo_forever', statements: { SUBSTACK: bodyStmts } };
      }
      return {
        type: 'doggo_while',
        values: { CONDITION: parseExpr(cond, vars) },
        statements: { SUBSTACK: bodyStmts },
      };
    }

    default:
      throw new ParseError(
        `Line ${line}: '${node.type}' is not supported — only doggo function calls, variable assignments, for/while loops are allowed`,
        line,
      );
  }
};

// ── Assignment parsing ───────────────────────────────────────────────────────

const parseAssignment = (node: Node, vars: Map<string, string>, line: number): BlockData => {
  const left = node.childForFieldName('left');
  const right = node.childForFieldName('right');
  if (!left || !right) {
    throw new ParseError(`Line ${line}: malformed assignment`, line);
  }
  if (left.type !== 'identifier') {
    throw new ParseError(
      `Line ${line}: can only assign to simple variables, not '${left.type}'`,
      line,
    );
  }
  const varName = left.text;
  const varId = resolveVar(varName, vars);
  return {
    type: 'variables_set',
    fields: { VAR: { value: varName, id: varId } },
    values: { VALUE: parseExpr(right, vars) },
  };
};

// ── Call parsing ─────────────────────────────────────────────────────────────

const NO_ARG_BLOCK_MAP = new Map(
  [...POSE_COMMANDS, ...TRICK_COMMANDS].map((d) => [d.functionName, d.blockType]),
);
const MOTION_COMMAND_MAP = new Map(MOTION_COMMANDS.map((d) => [d.functionName, d]));

const parseCallStmt = (node: Node, vars: Map<string, string>): BlockData => {
  const fn = node.childForFieldName('function');
  const argList = node.childForFieldName('arguments');
  const line = node.startPosition.row + 1;

  if (!fn) {
    throw new ParseError(`Line ${line}: malformed call`, line);
  }

  // time.sleep(N) → doggo_wait
  if (fn.type === 'attribute') {
    const obj = fn.childForFieldName('object');
    const attr = fn.childForFieldName('attribute');
    if (obj?.text === 'time' && attr?.text === 'sleep') {
      const argNodes = argList ? namedChildren(argList) : [];
      if (argNodes.length !== 1) {
        throw new ParseError(`Line ${line}: time.sleep() takes exactly one argument`, line);
      }
      return { type: 'doggo_wait', values: { SECONDS: parseExpr(argNodes[0], vars) } };
    }
    throw new ParseError(`Line ${line}: unknown call '${fn.text}'`, line);
  }

  if (fn.type !== 'identifier') {
    throw new ParseError(`Line ${line}: unsupported call expression`, line);
  }

  const name = fn.text;
  const argNodes = argList ? namedChildren(argList) : [];

  const noArgBlockType = NO_ARG_BLOCK_MAP.get(name);
  if (noArgBlockType !== undefined) {
    if (argNodes.length !== 0) {
      throw new ParseError(`Line ${line}: ${name}() takes no arguments`, line);
    }
    return { type: noArgBlockType };
  }

  const motionDef = MOTION_COMMAND_MAP.get(name);
  if (motionDef !== undefined) {
    const kw = argNodes.length === 1 ? argNodes[0] : null;
    if (!kw || kw.type !== 'keyword_argument') {
      throw new ParseError(
        `Line ${line}: ${name}() expects ${motionDef.param}=<number>, e.g. ${name}(${motionDef.param}=3)`,
        line,
      );
    }
    const key = kw.childForFieldName('name');
    const val = kw.childForFieldName('value');
    if (!key || key.text !== motionDef.param || !val) {
      throw new ParseError(
        `Line ${line}: ${name}() expects ${motionDef.param}=<number>, e.g. ${name}(${motionDef.param}=3)`,
        line,
      );
    }
    return {
      type: motionDef.blockType,
      values: { [motionDef.param.toUpperCase()]: parseExpr(val, vars) },
    };
  }

  throw new ParseError(`Line ${line}: unknown function '${name}'`, line);
};

// ── Expression parsing ───────────────────────────────────────────────────────

const BINARY_OPS: Record<string, string> = {
  '+': 'doggo_add',
  '-': 'doggo_sub',
  '*': 'doggo_mul',
  '/': 'doggo_div',
};

const COMPARE_OPS: Record<string, string> = {
  '<': 'doggo_lt',
  '>': 'doggo_gt',
  '==': 'doggo_eq',
  '<=': 'doggo_lte',
  '>=': 'doggo_gte',
};

const parseExpr = (node: Node, vars: Map<string, string>): BlockData => {
  const line = node.startPosition.row + 1;

  switch (node.type) {
    case 'integer':
    case 'float':
      return { type: 'math_number', fields: { NUM: { value: node.text } } };

    case 'identifier': {
      const id = resolveVar(node.text, vars);
      return { type: 'variables_get', fields: { VAR: { value: node.text, id } } };
    }

    case 'parenthesized_expression': {
      const inner = namedChildren(node)[0];
      if (!inner) {
        throw new ParseError(`Line ${line}: empty parentheses`, line);
      }
      return parseExpr(inner, vars);
    }

    case 'binary_operator': {
      const left = node.childForFieldName('left');
      const right = node.childForFieldName('right');
      const op = allChildren(node).find((c) => !c.isNamed && c.type in BINARY_OPS)?.type;
      if (!left || !right || !op) {
        throw new ParseError(`Line ${line}: malformed arithmetic expression`, line);
      }
      const blockType = BINARY_OPS[op];
      return {
        type: blockType,
        values: { A: parseExpr(left, vars), B: parseExpr(right, vars) },
      };
    }

    case 'comparison_operator': {
      // tree-sitter-python: namedChildren are the operands; operator sits between as anon node
      const operands = namedChildren(node);
      if (operands.length !== 2) {
        throw new ParseError(`Line ${line}: only simple comparisons (a OP b) are supported`, line);
      }
      const op = allChildren(node).find((c) => !c.isNamed && c.type in COMPARE_OPS)?.type;
      if (!op) {
        throw new ParseError(`Line ${line}: unsupported comparison operator`, line);
      }
      return {
        type: COMPARE_OPS[op],
        values: { A: parseExpr(operands[0], vars), B: parseExpr(operands[1], vars) },
      };
    }

    case 'boolean_operator': {
      const left = node.childForFieldName('left');
      const right = node.childForFieldName('right');
      const opNode = allChildren(node).find((c) => c.type === 'and' || c.type === 'or');
      if (!left || !right || !opNode) {
        throw new ParseError(`Line ${line}: malformed boolean expression`, line);
      }
      return {
        type: opNode.type === 'and' ? 'doggo_and' : 'doggo_or',
        values: { A: parseExpr(left, vars), B: parseExpr(right, vars) },
      };
    }

    case 'not_operator': {
      const arg = node.childForFieldName('argument');
      if (!arg) {
        throw new ParseError(`Line ${line}: malformed 'not' expression`, line);
      }
      return { type: 'doggo_not', values: { VALUE: parseExpr(arg, vars) } };
    }

    default:
      throw new ParseError(
        `Line ${line}: '${node.type}' is not a supported expression — only numbers, variables, and arithmetic/comparison operators are allowed`,
        line,
      );
  }
};

// ── Helpers ──────────────────────────────────────────────────────────────────

const resolveVar = (name: string, vars: Map<string, string>): string => {
  if (!vars.has(name)) {
    vars.set(name, crypto.randomUUID());
  }
  return vars.get(name)!;
};

const firstErrorNode = (node: Node): Node | null => {
  if (node.isError) {
    return node;
  }
  for (const child of allChildren(node)) {
    const found = firstErrorNode(child);
    if (found) {
      return found;
    }
  }
  return null;
};
